theme: jekyll-theme-minimal
title: Bounded Labs
description: Experimental Company Creation
logo: ![Primary Logo](https://github.com/BrienBounded/Bounded-Labs/raw/gh-pages/Primary%20Logo.png)
show_downloads: false
